apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapchat-user-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: mapchat-user
        image: chris360/mapchat-user:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mapchat-user-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002